// Generated by LiveScript 1.5.0
(function(){
  var Game;
  Game = require('game.ls').Game;
  window.onload = function(){
    return $.when($.getJSON("/data/stages.json"), $.getJSON("/data/config.json")).done(function(arg$, arg1$){
      var stages, config;
      stages = arg$[0];
      config = arg1$[0];
      return new Game(stages, config);
    });
  };
}).call(this);
