// Generated by LiveScript 1.5.0
(function(){
  var Text, out$ = typeof exports != 'undefined' && exports || this;
  out$.Text = Text = {
    makeText: function(sprite){
      var game, content, ref$, centerX, centerY, x, y, width, height, text;
      game = this.game;
      content = game.cache.getText("text_" + sprite.name);
      ref$ = this.game.world, centerX = ref$.centerX, centerY = ref$.centerY, x = ref$.x, y = ref$.y, width = ref$.width, height = ref$.height;
      text = game.add.text(0, 0, content);
      text.align = 'center';
      text.boundsAlignH = 'center';
      text.boundsAlignV = 'center';
      text.setTextBounds(x, y, width, height);
      text.fontSize = 30;
      text.fill = '#ffffff';
      text.stroke = '#000000';
      text.strokeThickness = 10;
      return sprite.text = text;
    }
  };
}).call(this);
